# Generated by Django 4.1.5 on 2023-01-21 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MemberName', models.CharField(max_length=100, unique=True)),
                ('MemberPrice', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TicketOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Date', models.DateTimeField(auto_now_add=True)),
                ('TicketCode', models.CharField(blank=True, max_length=5, unique=True)),
                ('Usage', models.CharField(max_length=100)),
                ('OrderType', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.member')),
            ],
        ),
    ]
