# Generated by Django 4.1.5 on 2023-01-21 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketorder',
            name='Usage',
        ),
        migrations.AddField(
            model_name='ticketorder',
            name='Validation',
            field=models.BooleanField(default=0),
        ),
        migrations.AlterField(
            model_name='ticketorder',
            name='TicketCode',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
